server:
  port: 8090

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: usuarios-microservicio
          uri: lb://usuarios-microservicio
          predicates:
            - Path=/api/usuarios
        - id: api-wallet
          uri: lb://api-wallet
          predicates:
            - Path=/wallet
        - id: usuariosdh
          uri: lb://usuariosdh
          predicates:
            - Path=/api/alumnos


info:
  app:
    name: ${spring.application.name}

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway
