server:
  port: 8090
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: cursos
          uri: lb://cursos
          predicates:
            - Path=/api/cursos/**
        - id: examenes
          uri: lb://examenes
          predicates:
            - Path=/api/examenes/**
        - id: usuariosdh
          uri: lb://usuariosdh
          predicates:
            - Path=/api/alumnos/**
        - id: respuestas
          uri: lb://respuestas
          predicates:
            - Path=/api/respuestas/**


info:
  app:
    name: ${spring.application.name}

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway
