server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: respuestas
  data:
    mongodb:
      uri: mongodb://localhost:27017/db_respuestas

info:
  application:
    name: cursos

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/